# Generated by Django 4.2.26 on 2025-12-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('supper', 'Служба поддержки')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
