from pathlib import Path
import os
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ["*"]

# ========================
# Database
# ========================
USE_POSTGRES = config('USE_POSTGRES', default=False, cast=bool)

# Берём данные из твоего .env
DB_NAME = config('POSTGRES_DB', default='db.sqlite3')
DB_USER = config('POSTGRES_USER', default='')
DB_PASSWORD = config('POSTGRES_PASSWORD', default='')
DB_HOST = config('POSTGRES_HOST', default='db1')
DB_PORT = config('POSTGRES_PORT', default='5432')

if USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / DB_NAME,
        }
    }

# ========================
# Email
# ========================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# ========================
# Apps
# ========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',         # твой основной app
    'accounts',
    'phonenumber_field',
    'django_resized',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'django_filters',
    'product',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ========================
# Auth / REST
# ========================
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':12,
    'DEFAULT_FILTER_BACKENDS':[
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
}

# ========================
# Password validation
# ========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ========================
# Localization
# ========================
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Asia/Bishkek'
USE_I18N = True
USE_TZ = True

# ========================
# Static / Media
# ========================
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================
# Celery / Redis
# ========================
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))

CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'










# """
# Django settings for core project.

# Generated by 'django-admin startproject' using Django 4.2.26.

# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """

# from pathlib import Path
# import environ
# import os
# from decouple import config

# BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET_KEY = config('SECRET_KEY')
# DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS = ["*"]

# USE_POSTGRES = config('USE_POSTGRES', default=False, cast=bool)
# DB_NAME = config('DB_NAME', default='db.sqlite3')
# DB_USER = config('DB_USER', default='')
# DB_PASSWORD = config('DB_PASSWORD', default='')
# DB_HOST = config('DB_HOST', default='localhost')
# DB_PORT = config('DB_PORT', default='5432')


# EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')

# EMAIL_HOST = os.getenv('EMAIL_HOST')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'

# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')



# if USE_POSTGRES:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': DB_NAME,
#             'USER': DB_USER,
#             'PASSWORD': DB_PASSWORD,
#             'HOST': DB_HOST,
#             'PORT': DB_PORT,
#         }
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / DB_NAME,
#         }
#     }

# # # ========================
# # # 1. Подключаем .env
# # # ========================
# # env = environ.Env(
# #     DEBUG=(bool, False)
# # )
# # environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# # # ========================
# # # 2. Основные секреты
# # # ========================
# # SECRET_KEY = env('SECRET_KEY')
# # DEBUG = env.bool("DEBUG")
# # ALLOWED_HOSTS = ["*"]

# # # ========================
# # # 3. Email
# # # ========================
# # EMAIL_BACKEND = env('EMAIL_BACKEND')
# # EMAIL_HOST = env('EMAIL_HOST')
# # EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
# # EMAIL_PORT = env.int('EMAIL_PORT')
# # EMAIL_HOST_USER = env('EMAIL_HOST_USER')
# # EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
# # DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# # # ========================
# # # 4. Database
# # # ========================
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': env('DB_NAME'),
# #         'USER': env('DB_USER'),
# #         'PASSWORD': env('DB_PASSWORD'),
# #         'HOST': env('DB_HOST'),
# #         'PORT': env.int('DB_PORT'),
# #     }
# # }



# # Application definition
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'main',
#     'accounts',
#     'phonenumber_field',
#     'django_resized',
#     'rest_framework',
#     'rest_framework.authtoken',
#     'drf_yasg',
#     'django_filters',
#     'product',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'core.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'core.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# # ============ Database SQLITE3 ============
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }

# # # ============ Database POSTGRESQL ===========
# # DATABASES =  {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME' : '',
# #         'USER' : '',
# #         'PASSWORD' :'',
# #         'HOST' : 'localhost',
# #         'PORT' : '5432'
# #     }
# # }


# # Password validation
# # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# AUTH_USER_MODEL = 'accounts.User'

# # Internationalization
# # https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'ru'

# TIME_ZONE = 'Asia/Bishkek'

# USE_I18N = True

# USE_TZ = True

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.BasicAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework.authentication.TokenAuthentication',
#     ],

#     'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE':12,

#     'DEFAULT_FILTER_BACKENDS':[
#         'django_filters.rest_framework.DjangoFilterBackend'
#     ],
    
# }


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = "/static/"

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# STATIC_ROOT = BASE_DIR / "staticfiles"

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# # EMAIL_HOST = 'smtp.gmail.com'
# # EMAIL_USE_TLS = True
# # EMAIL_PORT = 587

# # # EMAIL_HOST = 'smtp.yandex.com'
# # # EMAIL_USE_SSL = True
# # # EMAIL_PORT = 465

# # EMAIL_HOST_USER = 'user@gmail.com'
# # EMAIL_HOST_PASSWORD = 'КОД ИЗ google my account create app password'

# # DEFAULT_FROM_EMAIL = 'user@gmail.com'

# REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
# REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))

# CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
# CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'


# # REDIS_HOST = os.getenv('REDIS_HOST')
# # REDIS_PORT = os.getenv('REDIS_PORT')

# # CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379/0'
# # CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}
# # CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'
# # CELERY_ACCEPT_CONTENT = ['application/json']
# # CELERY_TASK_SERIALIZER = 'json'
# # CELERY_RESULT_SERIALIZER = 'json'
