# Generated by Django 4.2.26 on 2026-01-16 11:06

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер квартиры')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('rooms_count', models.IntegerField(verbose_name='Количество комнат')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь в квадратных метрах')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='apartments/', verbose_name='Изображение квартиры')),
                ('type', models.CharField(choices=[('studio', 'Студия'), ('standart', 'Стандартная'), ('comercial', 'Коммерческая'), ('penthouse', 'Пентхаус')], default='standart', max_length=20, verbose_name='Тип квартиры')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['block', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блока')),
                ('floor_count', models.IntegerField(verbose_name='Количество этажей в блоке')),
                ('type', models.CharField(choices=[('elit', 'Элитный'), ('simple', 'Простой')], default='simple', max_length=20, verbose_name='Типы блока')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес объекта')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects/', verbose_name='Изображение объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects_photo/', verbose_name='Изображения обьекта')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.object')),
            ],
            options={
                'verbose_name': 'Изображения обьекта',
                'verbose_name_plural': 'Изображения обьектов',
            },
        ),
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='blocks_photo/', verbose_name='Изображения блока')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.block')),
            ],
            options={
                'verbose_name': 'Изображения блока',
                'verbose_name_plural': 'Изображения блоков',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.object', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='ApartmnentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='apartments_photo/', verbose_name='Изображения квартиры')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.apartment')),
            ],
            options={
                'verbose_name': 'Изображения квартиры',
                'verbose_name_plural': 'Изображения квартир',
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='main.block', verbose_name='Блок'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('number', 'block')},
        ),
    ]
