# Generated by Django 4.2.26 on 2025-11-26 11:08

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес объекта')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects/', verbose_name='Изображение объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блока')),
                ('floor_count', models.IntegerField(verbose_name='Количество этажей в блоке')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер квартиры')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('rooms_count', models.IntegerField(verbose_name='Количество комнат')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь в квадратных метрах')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='apartments/', verbose_name='Изображение квартиры')),
                ('type', models.CharField(choices=[('studio', 'Студия'), ('standart', 'Стандартная'), ('comercial', 'Коммерческая'), ('penthouse', 'Пентхаус')], default='standart', max_length=20, verbose_name='Тип квартиры')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='main.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['block', 'floor', 'number'],
                'unique_together': {('number', 'block')},
            },
        ),
    ]
