# Generated by Django 4.2.26 on 2025-12-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_objectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectimage',
            options={'verbose_name': 'Изображения обьекта', 'verbose_name_plural': 'Изображения обьектов'},
        ),
    ]
