# Generated by Django 4.2.26 on 2025-12-11 04:50

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_objectimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='objects_photo/', verbose_name='Изображения обьекта'),
        ),
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='blocks_photo/', verbose_name='Изображения блока')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.block')),
            ],
            options={
                'verbose_name': 'Изображения блока',
                'verbose_name_plural': 'Изображения блоков',
            },
        ),
        migrations.CreateModel(
            name='ApartmnentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[800, 600], upload_to='apartments_photo/', verbose_name='Изображения квартиры')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.apartment')),
            ],
            options={
                'verbose_name': 'Изображения квартиры',
                'verbose_name_plural': 'Изображения квартир',
            },
        ),
    ]
